routes/web.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use App\Mail\UserWelcome;
use App\Models\DataDeletion;
use App\Models\Order;
use Illuminate\Support\Facades\DB;
use App\Models\Policy;
use App\Models\Privacy;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('policy', function () {
    $policy = Policy::where('id', 1)->first();
    return view('policy', ['policy' => $policy]);
});

Route::get('privacy', function () {
    $privacy = Privacy::where('id', 1)->first();
    return view('privacy', ['privacy' => $privacy]);
});

Route::get('data-deletions', function () {
    $data_deletions = DataDeletion::where('id', 1)->first();
    return view('data-deletions', ['data_deletions' => $data_deletions]);
});

Route::post('policy-update', [PolicyController::class, 'updatePolicy'])->name('policy-update');
Route::post('privacy-update', [PrivacyController::class, 'updatePrivacy'])->name('privacy-update');

Route::get('delete-account', function () {
    return view('delete-account');
});

Route::get('/verified-page', function (Request $request) {
    $code = $request->query('code');
    return view('verified-page', ['code' => $code]);
})->name('verified-page');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


// Route::group(['middleware' => ['auth:sanctum']], function() {
//     Route::resource('users', UserController::class);
// });

Route::get('/users', function () {
    $selected = [];
    return view('users', ['selected' => $selected]);
})->middleware('auth:sanctum')->name('users.index');

Route::group(['middleware' => ['auth:sanctum']], function() {
    Route::resource('orders', OrderController::class);
});

Route::get('/order/{orderId}', function ($orderId) {
    $order = Order::find($orderId);
    return view('order', ['order' => $order]);
})->middleware('auth:sanctum')->name('order.detail');

Route::get('/templates/users/{templateId}', function ($templateId) {
    $templateUsers = DB::table('glopcard_user_template')->where('template_id', $templateId)->get();
    $selected = array_map('strval', DB::table('glopcard_user_template')->where('template_id', $templateId)->get()->pluck('user_id')->toArray());

    return view('template-users', ['templateId' => $templateId, 'templateUsers' => $templateUsers, 'selected' => $selected]);
})->middleware('auth:sanctum')->name('template-users.detail');

Route::get('/order/{status}/{orderId}', [OrderController::class, 'setStatus'])->middleware('auth:sanctum')->name('order.status');

/* Route::group(['middleware' => ['auth:sanctum']], function() {
    Route::resource('templates', TemplateController::class);
}); */

Route::group(['middleware' => ['auth:sanctum', 'checkUserId']], function() {
    Route::resource('templates', TemplateController::class);
});

Route::group(['middleware' => ['auth:sanctum', 'checkUserId']], function() {
    Route::resource('posts', PostsController::class);
});


Route::get('/demo', function () {
    return new UserWelcome();
});

Route::get('/password/reset/{token}', function ($token) {
    return view('auth.reset-password', ['token' => $token]);
})->middleware('guest')->name('password.reset');

Route::get('/{glopcard}', [DynamicLinksController::class, 'previewCard']);

// Route::get('/{glopcard}', function ($glopcardId) {

// });

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/data-deletions.blade.php
<x-guest-layout>
    <div class="pt-4">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div><br>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
               
                {!! $data_deletions->data_deletions_content !!}


            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/delete-account.blade.php
<x-guest-layout>
    <div class="pt-4">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div><br>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                
<p class=MsoNormal><b><span lang=ES-MX style='font-family:"Arial",sans-serif;
mso-ansi-language:ES-MX'>Para eliminar tu cuenta sigue los siguientes pasos<o:p></o:p></span></b></p>

<p class=MsoListParagraphCxSpFirst ><![if !supportLists]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-fareast-font-family:Arial;
mso-ansi-language:ES-MX'><span style='mso-list:Ignore'>1.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-ansi-language:ES-MX'>Inicia
sesión en <span class=SpellE>glopcare</span><o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle ><![if !supportLists]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-fareast-font-family:Arial;
mso-ansi-language:ES-MX'><span style='mso-list:Ignore'>2.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-ansi-language:ES-MX'>Una
vez dentro, presiona el menú “Cuenta”<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle ><![if !supportLists]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-fareast-font-family:Arial;
mso-ansi-language:ES-MX'><span style='mso-list:Ignore'>3.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-ansi-language:ES-MX'>Selecciona
la pestaña “Configuración”<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle ><![if !supportLists]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-fareast-font-family:Arial;
mso-ansi-language:ES-MX'><span style='mso-list:Ignore'>4.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-ansi-language:ES-MX'>Presiona
la opción “Eliminar cuenta”<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle ><![if !supportLists]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-fareast-font-family:Arial;
mso-ansi-language:ES-MX'><span style='mso-list:Ignore'>5.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-ansi-language:ES-MX'>Confirma
que deseas eliminar tu cuenta seleccionando la opción “ELIMINAR”. Esta acción
no se puede deshacer. Una vez que elimines tu cuenta, se borraran todos tus
registros asociados y relacionados en “<span class=SpellE>glopcare</span>”<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpLast ><![if !supportLists]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-fareast-font-family:Arial;
mso-ansi-language:ES-MX'><span style='mso-list:Ignore'>6.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=ES-MX style='font-family:"Arial",sans-serif;mso-ansi-language:ES-MX'>Recibe
un correo electrónico y/o SMS confirmando la eliminación de tu cuenta<o:p></o:p></span></p>

<p class=MsoNormal><b><span lang=ES-MX style='mso-ansi-language:ES-MX'><o:p>&nbsp;</o:p></span></b></p>

<p class=MsoNormal><b><span lang=ES-MX style='mso-ansi-language:ES-MX'><o:p>&nbsp;</o:p></span></b></p>


            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/delete-mail.blade.php
@component('mail::message')
    {{-- Greeting --}}
    @if (!empty($greeting))
        # {{ $greeting }}
    @else
        @if ($level === 'error')
            # @lang('Whoops!')
        @else
            # @lang('Hello!')
        @endif
    @endif

 

  
@endcomponent

resources/views/dynamics.blade.php
<html>
    <head>
    @if($previewType == 'glopcard')
        <title>Glopcare | {{isset($snapshot->alias_name) ? $snapshot->alias_name : 'Usuario Glopcare'}}</title>
        <meta property="og:title" content="Glopcare | {{isset($snapshot->alias_name) ? $snapshot->alias_name : 'Usuario Glopcare'}}">
        <meta property="og:description" content="{{isset($snapshot->professional_title) ? $snapshot->professional_title : ''}} | {{isset($snapshot->professional_description) ? $snapshot->professional_description : ''}}">
        <meta property="og:url" content="https://glopcare.com/{{$user->username}}">
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://glopcare.com/storage/uploads/{{$avatar}}?t=12345">
        <!-- <meta property="og:image:width" content="200">
        <meta property="og:image:height" content="200"> -->
        <meta property="og:image:type" content="image/png" />
    @endif
    </head>
    <script>
        const isCrawler = @json($isCrawler);
        if (!isCrawler) {
            setTimeout(function(){
                window.location.href = 'https://glopcard.glopcare.com/{{$previewData->uid}}';
            }, 100);
        }
      </script>
</html>

resources/views/navigation-menu.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <img src="{{env('APP_URL')}}/img/square_logo.svg" class="block" style="width: 4rem;"/>
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-jet-nav-link>
                </div>
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('users.index') }}" :active="request()->routeIs('users')">
                        {{ __('Users') }}
                    </x-jet-nav-link>
                </div>
                @if (env('GLOPCARE_USER_ID') == auth()->user()->id)
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('templates.index') }}" :active="request()->routeIs('templates')">
                        {{ __('Templates') }}
                    </x-jet-nav-link>
                </div>
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('posts.index') }}" :active="request()->routeIs('posts')">
                        {{ __('Posts') }}
                    </x-jet-nav-link>
                </div>
                @endif
            </div>

            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="ml-3 relative">
                        <x-jet-dropdown align="right" width="60">
                            <x-slot name="trigger">
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:bg-gray-50 active:bg-gray-50 transition">
                                        {{ Auth::user()->currentTeam->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            </x-slot>

                            <x-slot name="content">
                                <div class="w-60">
                                    <!-- Team Management -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Manage Team') }}
                                    </div>

                                    <!-- Team Settings -->
                                    <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                        {{ __('Team Settings') }}
                                    </x-jet-dropdown-link>

                                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                        <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                            {{ __('Create New Team') }}
                                        </x-jet-dropdown-link>
                                    @endcan

                                    <div class="border-t border-gray-100"></div>

                                    <!-- Team Switcher -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Switch Teams') }}
                                    </div>

                                    @foreach (Auth::user()->allTeams() as $team)
                                        <x-jet-switchable-team :team="$team" />
                                    @endforeach
                                </div>
                            </x-slot>
                        </x-jet-dropdown>
                    </div>
                @endif

                <!-- Settings Dropdown -->
                <div class="ml-3 relative">
                    <x-jet-dropdown align="right" width="48">
                        <x-slot name="trigger">
                            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition">
                                    <img class="h-8 w-8 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                </button>
                            @else
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition">
                                        {{ Auth::user()->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            @endif
                        </x-slot>

                        <x-slot name="content">
                            <!-- Account Management -->
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Manage Account') }}
                            </div>

                            <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                {{ __('Profile') }}
                            </x-jet-dropdown-link>

                            @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                    {{ __('API Tokens') }}
                                </x-jet-dropdown-link>
                            @endif

                            <div class="border-t border-gray-100"></div>

                            <!-- Authentication -->
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-jet-dropdown-link>
                            </form>
                        </x-slot>
                    </x-jet-dropdown>
                </div>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                    <div class="shrink-0 mr-3">
                        <img class="h-10 w-10 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                    </div>
                @endif

                <div>
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                    this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                        <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                            {{ __('Create New Team') }}
                        </x-jet-responsive-nav-link>
                    @endcan

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
    </div>
</nav>

resources/views/order.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Order Detail') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Order Status') }} {{ $order->status }}
            </h2>
            <a href="{{ route('order.status', ['status' => 'inprogress', 'orderId' => $order->id]) }}">
                <x-jet-button href="{{ route('order.status', ['status' => 'inprogress', 'orderId' => $order->id]) }}">
                    {{ __('Set In Progress') }}
                </x-jet-button>
            </a>
            <a href="{{ route('order.status', ['status' => 'delivered', 'orderId' => $order->id]) }}">
                <x-jet-button href="{{ route('order.status', ['status' => 'delivered', 'orderId' => $order->id]) }}">
                    {{ __('Set Delivered') }}
                </x-jet-button>
            </a>
            <a href="{{ route('order.status', ['status' => 'cancelled', 'orderId' => $order->id]) }}">
                <x-jet-button href="{{ route('order.status', ['status' => 'cancelled', 'orderId' => $order->id]) }}">
                    {{ __('Cancel Order') }}
                </x-jet-button>
            </a>
            <br>
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="bg-gray-200 bg-opacity-25">

                    <livewire:order-table :orderId="$order->id" />
                </div>
            </div>
            <br>

            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Order Payment Methods') }}
            </h2>
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="bg-gray-200 bg-opacity-25">

                    <livewire:order-payment-methods-table :orderId="$order->id" />
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/orders.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Orders') }}
    </h2>
  </x-slot>
  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
        <div class="bg-gray-200 bg-opacity-25">

          <livewire:orders-table />
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div><br>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
               
                {!! $policy->policies_content !!}


            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/posts.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Posts') }}
        </h2>
    </x-slot>

    <div>
        <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
            
          
            @livewire('posts.update-policy-form')

            <x-jet-section-border />



            <div class="mt-10 sm:mt-0">
                @livewire('posts.update-privacy-form')
            </div>

            <x-jet-section-border />


            <div class="mt-10 sm:mt-0">
                @livewire('posts.update-data-deletions-form')
            </div>

            <x-jet-section-border />
        </div>
    </div>
</x-app-layout>

resources/views/template-users.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Visibilidad de la Plantilla') }}
    </h2>
  </x-slot>
  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ is_null($templateUsers->first()) ? 'Esta plantilla la pueden ver todos' : 'Esta plantilla solo la pueden ver los usuarios seleccionados' }}
      </h2>
      <br>
      <h3 class="font-semibold text-l text-gray-800 leading-tight">
        {{ is_null($templateUsers->first()) ? 'Al agregar nuevos usuarios, controla la visibilidad. Las plantillas que ya se hayan creado usando esta plantilla seguirán funcionando' : 'Si desactiva todos los usuarios, la plantilla será pública' }}
      </h3>
      <br>
      <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
        <div class="bg-gray-200 bg-opacity-25">
          <livewire:template-users-table :templateId="$templateId" :selected="$selected"/>
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/templates.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Templates') }}
    </h2>
  </x-slot>

  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
        <div class="bg-gray-200 bg-opacity-25">
          
          <livewire:templates-table />
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/users.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
      {{ __('Users') }}
    </h2>
  </x-slot>
  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
        <div class="bg-gray-200 bg-opacity-25">

          <livewire:users-table :selected="$selected"/>
        </div>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/verified-page.blade.php
<x-guest-layout>
    <x-jet-authentication-card>
        <x-slot name="logo">
            <x-jet-authentication-card-logo />
        </x-slot>

        <x-jet-validation-errors class="mb-4" />


        <div class="mb-4 font-medium text-sm text-green-600">
            @if ($code == '002') <p class="text-center">
                <strong>Usuario ya ha sido autenticado</strong>
            </p>
       
    @elseif ($code == '001')
        <p class="text-center">
            <strong>Tu cuenta ha sido confirmada</strong><br>
            Ya puedes ingresar a tu App Glopcare
        </p>
    @endif
        </div>


    </x-jet-authentication-card>
</x-guest-layout>